const lorem = `<p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
  <p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
  <p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
  <p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
  <p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
  <p>
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی. متن اصلی کتاب درسی آزمایشی.
  </p>
`;

export const contentOfBooks = {
  "علوم تجربی ۷": [
    { id: 1, content: lorem },
    { id: 2, content: lorem },
    { id: 3, content: lorem },
    { id: 4, content: lorem },
    { id: 5, content: lorem },
    { id: 6, content: lorem },
    { id: 7, content: lorem },
    { id: 8, content: lorem },
    { id: 9, content: lorem },
    { id: 10, content: lorem },
    { id: 11, content: lorem },
    { id: 12, content: lorem },
    { id: 13, content: lorem },
    { id: 14, content: lorem },
    { id: 15, content: lorem },
    { id: 16, content: lorem },
    { id: 17, content: lorem },
    { id: 18, content: lorem },
    { id: 19, content: lorem },
    { id: 20, content: lorem },
    { id: 21, content: lorem },
    { id: 22, content: lorem },
    { id: 23, content: lorem },
    { id: 24, content: lorem },
    { id: 25, content: lorem },
    { id: 26, content: lorem },
    { id: 27, content: lorem },
    { id: 28, content: lorem },
    { id: 29, content: lorem },
    { id: 30, content: lorem },
    { id: 31, content: lorem },
    { id: 32, content: lorem },
    { id: 33, content: lorem },
    { id: 34, content: lorem },
    { id: 35, content: lorem },
    { id: 36, content: lorem },
    { id: 37, content: lorem },
    { id: 38, content: lorem },
    { id: 39, content: lorem },
    { id: 40, content: lorem },
    { id: 41, content: lorem },
    { id: 42, content: lorem },
    { id: 43, content: lorem },
    { id: 44, content: lorem },
    { id: 45, content: lorem },
    { id: 46, content: lorem },
    { id: 47, content: lorem },
    { id: 48, content: lorem },
    { id: 49, content: lorem },
    { id: 50, content: lorem },
    { id: 51, content: lorem },
    { id: 52, content: lorem },
    { id: 53, content: lorem },
    { id: 54, content: lorem },
    { id: 55, content: lorem },
    { id: 56, content: lorem },
    { id: 57, content: lorem },
    { id: 58, content: lorem },
    { id: 59, content: lorem },
    { id: 60, content: lorem },
    { id: 61, content: lorem },
    { id: 62, content: lorem },
    { id: 63, content: lorem },
    { id: 64, content: lorem },
    { id: 65, content: lorem },
    { id: 66, content: lorem },
    { id: 67, content: lorem },
    { id: 68, content: lorem },
    { id: 69, content: lorem },
    { id: 70, content: lorem },
    { id: 71, content: lorem },
    { id: 72, content: lorem },
    { id: 73, content: lorem },
    { id: 74, content: lorem },
    { id: 75, content: lorem },
    { id: 76, content: lorem },
    { id: 77, content: lorem },
    { id: 78, content: lorem },
    { id: 79, content: lorem },
    { id: 80, content: lorem },
    { id: 81, content: lorem },
    { id: 82, content: lorem },
    { id: 83, content: lorem },
    { id: 84, content: lorem },
    { id: 85, content: lorem },
    { id: 86, content: lorem },
    { id: 87, content: lorem },
    { id: 88, content: lorem },
    { id: 89, content: lorem },
    { id: 90, content: lorem },
    { id: 91, content: lorem },
    { id: 92, content: lorem },
    { id: 93, content: lorem },
    { id: 94, content: lorem },
    { id: 95, content: lorem },
    { id: 96, content: lorem },
    { id: 97, content: lorem },
    { id: 98, content: lorem },
    { id: 99, content: lorem },
    { id: 100, content: lorem },
    { id: 101, content: lorem },
    { id: 102, content: lorem },
    { id: 103, content: lorem },
    { id: 104, content: lorem },
    { id: 105, content: lorem },
    { id: 106, content: lorem },
    { id: 107, content: lorem },
    { id: 108, content: lorem },
    { id: 109, content: lorem },
    { id: 110, content: lorem },
    { id: 111, content: lorem },
    { id: 112, content: lorem },
    { id: 113, content: lorem },
    { id: 114, content: lorem },
    { id: 115, content: lorem },
    { id: 116, content: lorem },
    { id: 117, content: lorem },
    { id: 118, content: lorem },
    { id: 119, content: lorem },
    { id: 120, content: lorem },
    { id: 121, content: lorem },
    { id: 122, content: lorem },
    { id: 123, content: lorem },
    { id: 124, content: lorem },
    { id: 125, content: lorem },
    { id: 126, content: lorem },
    { id: 127, content: lorem },
    { id: 128, content: lorem },
    { id: 129, content: lorem },
    { id: 130, content: lorem },
    { id: 131, content: lorem },
    { id: 132, content: lorem },
    { id: 133, content: lorem },
    { id: 134, content: lorem },
    { id: 135, content: lorem },
    { id: 136, content: lorem },
    { id: 137, content: lorem },
    { id: 138, content: lorem },
    { id: 139, content: lorem },
    { id: 140, content: lorem },
    { id: 141, content: lorem },
    { id: 142, content: lorem },
    { id: 143, content: lorem },
    { id: 144, content: lorem },
    { id: 145, content: lorem },
    { id: 146, content: lorem },
    { id: 147, content: lorem },
    { id: 148, content: lorem },
    { id: 149, content: lorem },
    { id: 150, content: lorem },
    { id: 151, content: lorem },
    { id: 152, content: lorem },
    { id: 153, content: lorem },
    { id: 154, content: lorem },
    { id: 155, content: lorem },
    { id: 156, content: lorem },
    { id: 157, content: lorem },
    { id: 158, content: lorem },
    { id: 159, content: lorem },
    { id: 160, content: lorem },
    { id: 161, content: lorem },
    { id: 162, content: lorem },
    { id: 163, content: lorem },
    { id: 164, content: lorem },
    { id: 165, content: lorem },
    { id: 166, content: lorem },
    { id: 167, content: lorem },
    { id: 168, content: lorem },
    { id: 169, content: lorem },
    { id: 170, content: lorem },
    { id: 171, content: lorem },
    { id: 172, content: lorem },
    { id: 173, content: lorem },
    { id: 174, content: lorem },
    { id: 175, content: lorem },
    { id: 176, content: lorem },
  ],
  "علوم تجربی ۸": [
    { id: 1, content: lorem },
    { id: 2, content: lorem },
    { id: 3, content: lorem },
    { id: 4, content: lorem },
    { id: 5, content: lorem },
    { id: 6, content: lorem },
    { id: 7, content: lorem },
    { id: 8, content: lorem },
    { id: 9, content: lorem },
    { id: 10, content: lorem },
    { id: 11, content: lorem },
    { id: 12, content: lorem },
    { id: 13, content: lorem },
    { id: 14, content: lorem },
    { id: 15, content: lorem },
    { id: 16, content: lorem },
    { id: 17, content: lorem },
    { id: 18, content: lorem },
    { id: 19, content: lorem },
    { id: 20, content: lorem },
    { id: 21, content: lorem },
    { id: 22, content: lorem },
    { id: 23, content: lorem },
    { id: 24, content: lorem },
    { id: 25, content: lorem },
    { id: 26, content: lorem },
    { id: 27, content: lorem },
    { id: 28, content: lorem },
    { id: 29, content: lorem },
    { id: 30, content: lorem },
    { id: 31, content: lorem },
    { id: 32, content: lorem },
    { id: 33, content: lorem },
    { id: 34, content: lorem },
    { id: 35, content: lorem },
    { id: 36, content: lorem },
    { id: 37, content: lorem },
    { id: 38, content: lorem },
    { id: 39, content: lorem },
    { id: 40, content: lorem },
    { id: 41, content: lorem },
    { id: 42, content: lorem },
    { id: 43, content: lorem },
    { id: 44, content: lorem },
    { id: 45, content: lorem },
    { id: 46, content: lorem },
    { id: 47, content: lorem },
    { id: 48, content: lorem },
    { id: 49, content: lorem },
    { id: 50, content: lorem },
    { id: 51, content: lorem },
    { id: 52, content: lorem },
    { id: 53, content: lorem },
    { id: 54, content: lorem },
    { id: 55, content: lorem },
    { id: 56, content: lorem },
    { id: 57, content: lorem },
    { id: 58, content: lorem },
    { id: 59, content: lorem },
    { id: 60, content: lorem },
    { id: 61, content: lorem },
    { id: 62, content: lorem },
    { id: 63, content: lorem },
    { id: 64, content: lorem },
    { id: 65, content: lorem },
    { id: 66, content: lorem },
    { id: 67, content: lorem },
    { id: 68, content: lorem },
    { id: 69, content: lorem },
    { id: 70, content: lorem },
    { id: 71, content: lorem },
    { id: 72, content: lorem },
    { id: 73, content: lorem },
    { id: 74, content: lorem },
    { id: 75, content: lorem },
    { id: 76, content: lorem },
    { id: 77, content: lorem },
    { id: 78, content: lorem },
    { id: 79, content: lorem },
    { id: 80, content: lorem },
    { id: 81, content: lorem },
    { id: 82, content: lorem },
    { id: 83, content: lorem },
    { id: 84, content: lorem },
    { id: 85, content: lorem },
    { id: 86, content: lorem },
    { id: 87, content: lorem },
    { id: 88, content: lorem },
    { id: 89, content: lorem },
    { id: 90, content: lorem },
    { id: 91, content: lorem },
    { id: 92, content: lorem },
    { id: 93, content: lorem },
    { id: 94, content: lorem },
    { id: 95, content: lorem },
    { id: 96, content: lorem },
    { id: 97, content: lorem },
    { id: 98, content: lorem },
    { id: 99, content: lorem },
    { id: 100, content: lorem },
    { id: 101, content: lorem },
    { id: 102, content: lorem },
    { id: 103, content: lorem },
    { id: 104, content: lorem },
    { id: 105, content: lorem },
    { id: 106, content: lorem },
    { id: 107, content: lorem },
    { id: 108, content: lorem },
    { id: 109, content: lorem },
    { id: 110, content: lorem },
    { id: 111, content: lorem },
    { id: 112, content: lorem },
    { id: 113, content: lorem },
    { id: 114, content: lorem },
    { id: 115, content: lorem },
    { id: 116, content: lorem },
    { id: 117, content: lorem },
    { id: 118, content: lorem },
    { id: 119, content: lorem },
    { id: 120, content: lorem },
    { id: 121, content: lorem },
    { id: 122, content: lorem },
    { id: 123, content: lorem },
    { id: 124, content: lorem },
    { id: 125, content: lorem },
    { id: 126, content: lorem },
    { id: 127, content: lorem },
    { id: 128, content: lorem },
    { id: 129, content: lorem },
    { id: 130, content: lorem },
    { id: 131, content: lorem },
    { id: 132, content: lorem },
    { id: 133, content: lorem },
    { id: 134, content: lorem },
    { id: 135, content: lorem },
    { id: 136, content: lorem },
    { id: 137, content: lorem },
    { id: 138, content: lorem },
    { id: 139, content: lorem },
    { id: 140, content: lorem },
    { id: 141, content: lorem },
    { id: 142, content: lorem },
    { id: 143, content: lorem },
    { id: 144, content: lorem },
    { id: 145, content: lorem },
    { id: 146, content: lorem },
  ],
  "زیست شناسی ۱": [
    { id: 1, content: lorem },
    { id: 2, content: lorem },
    { id: 3, content: lorem },
    { id: 4, content: lorem },
    { id: 5, content: lorem },
    { id: 6, content: lorem },
    { id: 7, content: lorem },
    { id: 8, content: lorem },
    { id: 9, content: lorem },
    { id: 10, content: lorem },
    { id: 11, content: lorem },
    { id: 12, content: lorem },
    { id: 13, content: lorem },
    { id: 14, content: lorem },
    { id: 15, content: lorem },
    { id: 16, content: lorem },
    { id: 17, content: lorem },
    { id: 18, content: lorem },
    { id: 19, content: lorem },
    { id: 20, content: lorem },
    { id: 21, content: lorem },
    { id: 22, content: lorem },
    { id: 23, content: lorem },
    { id: 24, content: lorem },
    { id: 25, content: lorem },
    { id: 26, content: lorem },
    { id: 27, content: lorem },
    { id: 28, content: lorem },
    { id: 29, content: lorem },
    { id: 30, content: lorem },
    { id: 31, content: lorem },
    { id: 32, content: lorem },
    { id: 33, content: lorem },
    { id: 34, content: lorem },
    { id: 35, content: lorem },
    { id: 36, content: lorem },
    { id: 37, content: lorem },
    { id: 38, content: lorem },
    { id: 39, content: lorem },
    { id: 40, content: lorem },
    { id: 41, content: lorem },
    { id: 42, content: lorem },
    { id: 43, content: lorem },
    { id: 44, content: lorem },
    { id: 45, content: lorem },
    { id: 46, content: lorem },
    { id: 47, content: lorem },
    { id: 48, content: lorem },
    { id: 49, content: lorem },
    { id: 50, content: lorem },
    { id: 51, content: lorem },
    { id: 52, content: lorem },
    { id: 53, content: lorem },
    { id: 54, content: lorem },
    { id: 55, content: lorem },
    { id: 56, content: lorem },
    { id: 57, content: lorem },
    { id: 58, content: lorem },
    { id: 59, content: lorem },
    { id: 60, content: lorem },
    { id: 61, content: lorem },
    { id: 62, content: lorem },
    { id: 63, content: lorem },
    { id: 64, content: lorem },
    { id: 65, content: lorem },
    { id: 66, content: lorem },
    { id: 67, content: lorem },
    { id: 68, content: lorem },
    { id: 69, content: lorem },
    { id: 70, content: lorem },
    { id: 71, content: lorem },
    { id: 72, content: lorem },
    { id: 73, content: lorem },
    { id: 74, content: lorem },
    { id: 75, content: lorem },
    { id: 76, content: lorem },
    { id: 77, content: lorem },
    { id: 78, content: lorem },
    { id: 79, content: lorem },
    { id: 80, content: lorem },
    { id: 81, content: lorem },
    { id: 82, content: lorem },
    { id: 83, content: lorem },
    { id: 84, content: lorem },
    { id: 85, content: lorem },
    { id: 86, content: lorem },
    { id: 87, content: lorem },
    { id: 88, content: lorem },
    { id: 89, content: lorem },
    { id: 90, content: lorem },
    { id: 91, content: lorem },
    { id: 92, content: lorem },
    { id: 93, content: lorem },
    { id: 94, content: lorem },
    { id: 95, content: lorem },
    { id: 96, content: lorem },
    { id: 97, content: lorem },
    { id: 98, content: lorem },
    { id: 99, content: lorem },
    { id: 100, content: lorem },
    { id: 101, content: lorem },
    { id: 102, content: lorem },
    { id: 103, content: lorem },
    { id: 104, content: lorem },
    { id: 105, content: lorem },
    { id: 106, content: lorem },
    { id: 107, content: lorem },
    { id: 108, content: lorem },
    { id: 109, content: lorem },
    { id: 110, content: lorem },
    { id: 111, content: lorem },
    { id: 112, content: lorem },
    { id: 113, content: lorem },
    { id: 114, content: lorem },
    { id: 115, content: lorem },
    { id: 116, content: lorem },
    { id: 117, content: lorem },
    { id: 118, content: lorem },
    { id: 119, content: lorem },
    { id: 120, content: lorem },
    { id: 121, content: lorem },
    { id: 122, content: lorem },
    { id: 123, content: lorem },
    { id: 124, content: lorem },
    { id: 125, content: lorem },
    { id: 126, content: lorem },
    { id: 127, content: lorem },
    { id: 128, content: lorem },
    { id: 129, content: lorem },
    { id: 130, content: lorem },
    { id: 131, content: lorem },
    { id: 132, content: lorem },
    { id: 133, content: lorem },
    { id: 134, content: lorem },
    { id: 135, content: lorem },
    { id: 136, content: lorem },
    { id: 137, content: lorem },
    { id: 138, content: lorem },
    { id: 139, content: lorem },
    { id: 140, content: lorem },
    { id: 141, content: lorem },
    { id: 142, content: lorem },
    { id: 143, content: lorem },
    { id: 144, content: lorem },
    { id: 145, content: lorem },
    { id: 146, content: lorem },
    { id: 147, content: lorem },
    { id: 148, content: lorem },
    { id: 149, content: lorem },
    { id: 150, content: lorem },
    { id: 151, content: lorem },
    { id: 152, content: lorem },
    { id: 153, content: lorem },
    { id: 154, content: lorem },
    { id: 155, content: lorem },
    { id: 156, content: lorem },
    { id: 157, content: lorem },
    { id: 158, content: lorem },
    { id: 159, content: lorem },
    { id: 160, content: lorem },
    { id: 161, content: lorem },
    { id: 162, content: lorem },
    { id: 163, content: lorem },
    { id: 164, content: lorem },
    { id: 165, content: lorem },
    { id: 166, content: lorem },
    { id: 167, content: lorem },
    { id: 168, content: lorem },
    { id: 169, content: lorem },
    { id: 170, content: lorem },
    { id: 171, content: lorem },
    { id: 172, content: lorem },
    { id: 173, content: lorem },
    { id: 174, content: lorem },
    { id: 175, content: lorem },
    { id: 176, content: lorem },
  ],
};

// 1- gereftane data az server
export const fehrestsOfPurchasedBooks = {
  "علوم تجربی ۷": [
    { id: "1-0", refPage: 1, indent: 0, refTitle: "بخش ۱: علوم و ابزارهای آن" },
    { id: "1-1", refPage: 2, indent: 1, refTitle: "۱: تفکر و تجربه" },
    {
      id: "1-2",
      refPage: 6,
      indent: 1,
      refTitle: "۲. اندازه‌گیری در علوم و ابزارهای آن",
    },
    { id: "2-0", refPage: 12, indent: 0, refTitle: "بخش ۲: مواد در زندگی ما" },
    { id: "2-1", refPage: 13, indent: 1, refTitle: "۳. اتم‌ها؛ الفبای مواد" },
    { id: "2-2", refPage: 25, indent: 1, refTitle: "۴. مواد پیرامون ما" },
    {
      id: "3-0",
      refPage: 35,
      indent: 0,
      refTitle: "بخش ۳: منابع خدادادی در خدمت ما",
    },
    { id: "3-1", refPage: 36, indent: 1, refTitle: "۵. از معدن تا خانه" },
    { id: "3-2", refPage: 48, indent: 1, refTitle: "۶. سفر آب روی زمین" },
    { id: "3-3", refPage: 56, indent: 1, refTitle: "۷. سفر آب درون زمین" },
    {
      id: "4-0",
      refPage: 65,
      indent: 0,
      refTitle: "بخش ۴: انرژی؛ نیاز همیشگی",
    },
    { id: "4-1", refPage: 66, indent: 1, refTitle: "۸. انرژی و تبدیل‌های آن" },
    { id: "4-2", refPage: 77, indent: 1, refTitle: "۹. منابع انرژی" },
    {
      id: "4-3",
      refPage: 86,
      indent: 1,
      refTitle: "۱۰. گرما و بهینه‌سازی مصرف انرژی",
    },
    { id: "5-0", refPage: 98, indent: 0, refTitle: "بخش ۵: دنیای درون من" },
    {
      id: "5-1",
      refPage: 99,
      indent: 1,
      refTitle: "۱۱. یاخته و سازمان‌بندی آن",
    },
    { id: "5-2", refPage: 107, indent: 1, refTitle: "۱۲. سفره سلامت" },
    { id: "5-3", refPage: 116, indent: 1, refTitle: "۱۳. سفر غذا" },
    { id: "5-4", refPage: 124, indent: 1, refTitle: "۱۴. گردش مواد" },
    { id: "5-5", refPage: 132, indent: 1, refTitle: "۱۵. تبادل با محیط" },
  ],
  "علوم تجربی ۸": [
    { id: "1", refPage: 1, indent: 0, refTitle: "۱. مخلوط و جداسازی مواد" },
    {
      id: "2",
      refPage: 9,
      indent: 0,
      refTitle: "۲. تغییرهای شیمیایی در خدمت زندگی",
    },
    { id: "3", refPage: 21, indent: 0, refTitle: "۳. از درون اتم چه‌خبر" },
    { id: "4", refPage: 28, indent: 0, refTitle: "۴. تنظیم عصبی" },
    { id: "5", refPage: 35, indent: 0, refTitle: "۵. حس و حرکت" },
    { id: "6", refPage: 47, indent: 0, refTitle: "۶. تنظیم هورمونی" },
    { id: "7", refPage: 55, indent: 0, refTitle: "۷. الفبای زیست‌فناوری" },
    { id: "8", refPage: 65, indent: 0, refTitle: "۸. تولیدمثل در جانداران" },
    { id: "9", refPage: 76, indent: 0, refTitle: "۹. الکتریسیته" },
    { id: "10", refPage: 89, indent: 0, refTitle: "۱۰. مغناتیس" },
    { id: "11", refPage: 97, indent: 0, refTitle: "۱۱. کانی‌ها" },
    { id: "12", refPage: 104, indent: 0, refTitle: "۱۲. سنگ‌ها" },
    { id: "13", refPage: 114, indent: 0, refTitle: "۱۳. هوازدگی" },
    { id: "14", refPage: 122, indent: 0, refTitle: "۱۴. نور و ویژگی‌های آن" },
    { id: "15", refPage: 136, indent: 0, refTitle: "۱۵. شکست نور" },
  ],
  "زیست شناسی ۱": [
    { id: "1-0", refPage: 1, indent: 0, refTitle: "فصل ۱. دنیای زنده" },
    { id: "1-1", refPage: 2, indent: 1, refTitle: "گفتار ۱. زیست شناسی چیست؟" },
    { id: "1-2", refPage: 7, indent: 1, refTitle: "گفتار ۲. گستره حیات" },
    {
      id: "1-3",
      refPage: 11,
      indent: 1,
      refTitle: "گفتار ۳. یاخته و بافت در بدن انسان",
    },
    { id: "2-0", refPage: 17, indent: 0, refTitle: "فصل ۲. گوارش و جذب مواد" },
    {
      id: "2-1",
      refPage: 18,
      indent: 1,
      refTitle: "گفتار ۱. ساختار و عملکرد لوله گوارش",
    },
    {
      id: "2-2",
      refPage: 25,
      indent: 1,
      refTitle: "گفتار ۲. جذب مواد و تنظیم فعالیت دستگاه گوارش",
    },
    {
      id: "2-3",
      refPage: 30,
      indent: 1,
      refTitle: "گفتار ۳. تنوع گوارش در جانداران",
    },
    { id: "3-0", refPage: 33, indent: 0, refTitle: "فصل ۳. تبادلات گازی" },
    {
      id: "3-1",
      refPage: 34,
      indent: 1,
      refTitle: "گفتار ۱. ساز و کار دستگاه تنفس در انسان",
    },
    { id: "3-2", refPage: 40, indent: 1, refTitle: "گفتار ۲. تهویه ششی" },
    {
      id: "3-3",
      refPage: 45,
      indent: 1,
      refTitle: "گفتار ۳. تنوع در تبادلات گازی",
    },
    { id: "4-0", refPage: 47, indent: 0, refTitle: "فصل ۴. گردش مواد در بدن" },
    { id: "4-1", refPage: 48, indent: 1, refTitle: "گفتار ۱. قلب" },
    { id: "4-2", refPage: 55, indent: 1, refTitle: "گفتار ۲. رگ ها" },
    { id: "4-3", refPage: 61, indent: 1, refTitle: "گفتار ۳. خون" },
    {
      id: "4-4",
      refPage: 65,
      indent: 1,
      refTitle: "گفتار ۴. تنوع گردش مواد در جانداران",
    },
    {
      id: "5-0",
      refPage: 69,
      indent: 0,
      refTitle: "فصل ۵. تنظیم اسمزی و دفع مواد زائد",
    },
    {
      id: "5-1",
      refPage: 70,
      indent: 1,
      refTitle: "گفتار ۱. هم ایستایی و کلیه ها",
    },
    {
      id: "5-2",
      refPage: 73,
      indent: 1,
      refTitle: "گفتار ۲. تشکیل ادرار و تخلیه آن",
    },
    {
      id: "5-3",
      refPage: 76,
      indent: 1,
      refTitle: "گفتار ۳. تنوع دفع و تنظیم اسمزی در جانداران",
    },
    { id: "6-0", refPage: 79, indent: 0, refTitle: "فصل ۶. از یاخته تا گیاه" },
    {
      id: "6-1",
      refPage: 80,
      indent: 1,
      refTitle: "گفتار ۱. ویژگی های یاخته های گیاهی",
    },
    { id: "6-2", refPage: 86, indent: 1, refTitle: "گفتار ۲. سامانه بافتی" },
    { id: "6-3", refPage: 90, indent: 1, refTitle: "گفتار ۳. ساختار گیاهان" },
    {
      id: "7-0",
      refPage: 97,
      indent: 0,
      refTitle: "فصل ۷. جذب و انتقال مواد در گیاهان",
    },
    { id: "7-1", refPage: 98, indent: 1, refTitle: "گفتار ۱. تغذیه گیاهی" },
    {
      id: "7-2",
      refPage: 102,
      indent: 1,
      refTitle: "گفتار ۲. جانداران موثر در تغذیه گیاهی",
    },
    {
      id: "7-3",
      refPage: 105,
      indent: 1,
      refTitle: "گفتار ۳. انتقال مواد در گیاهان",
    },
  ],
};
